# Generated by Django 3.1.2 on 2020-11-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_orderitem_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
