# Generated by Django 3.1.2 on 2020-11-14 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20201113_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='category_name',
            new_name='category',
        ),
    ]
