# Generated by Django 3.1.2 on 2020-11-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_profilepicture_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_verify',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
